---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: conjur-authenticator-role-binding
  namespace: quincy
subjects:
  - kind: ServiceAccount
    name: conjur-oss
    namespace: conjur
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-oss-conjur-authenticator
